name: Build and Test

on: [push, pull_request]
  branches:
    - master
    
jobs:
  run-msbuild:
  runs-on: windows-latest
  name: Run MSBuild
  
  steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build app for release
      run: msbuild src\YourProjectFile.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
